import { AITool, ToolCategory, RelationType, Difficulty, Pricing } from './types';

export const AI_TOOLS: AITool[] = [
  // ============================================================
  // CORE CONCEPTS
  // ============================================================
  {
    id: 'llm',
    name: 'LLM (Large Language Model)',
    category: ToolCategory.CONCEPT,
    description: 'An AI model trained on massive amounts of text data to understand and generate human-like language. The "brain" behind tools like ChatGPT, Claude, and Gemini.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
  },
  {
    id: 'rag',
    name: 'RAG (Retrieval-Augmented Generation)',
    category: ToolCategory.CONCEPT,
    description: 'A technique that gives LLMs access to external data (like your company files) to provide more accurate, grounded answers instead of relying on training data alone.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    relations: [
      { targetId: 'vector-db', type: RelationType.DEPENDS_ON },
      { targetId: 'llm', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'embeddings', type: RelationType.DEPENDS_ON },
    ],
  },
  {
    id: 'vector-db',
    name: 'Vector Database',
    category: ToolCategory.CONCEPT,
    description: 'A database that stores data as mathematical "vectors" so AI can find related pieces of information based on meaning, not exact keyword matches.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
  },
  {
    id: 'embeddings',
    name: 'Embeddings',
    category: ToolCategory.CONCEPT,
    description: 'Turning text or images into a list of numbers (vectors) so a computer can understand context and similarity. The foundation of semantic search and RAG.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
  },
  {
    id: 'agentic-ai',
    name: 'Agentic AI',
    category: ToolCategory.CONCEPT,
    description: "AI systems that don't just chat — they perform tasks by using tools, browsing the web, calling APIs, and making decisions autonomously across multiple steps.",
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    relations: [
      { targetId: 'crew-ai', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'langgraph', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'function-calling', type: RelationType.DEPENDS_ON },
    ],
  },
  {
    id: 'tokenization',
    name: 'Tokenization',
    category: ToolCategory.CONCEPT,
    description: 'How AI "reads" text by breaking it into small chunks called tokens. Understanding tokens is critical for managing costs and context window limits.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
  },
  {
    id: 'function-calling',
    name: 'Function Calling / Tool Use',
    category: ToolCategory.CONCEPT,
    description: 'Letting an LLM trigger your code: it picks which function to call and what arguments to pass. The mechanism behind every modern AI agent.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    relations: [
      { targetId: 'agentic-ai', type: RelationType.IMPLEMENTS },
    ],
  },
  {
    id: 'mcp',
    name: 'Model Context Protocol (MCP)',
    category: ToolCategory.CONCEPT,
    description: 'An open standard introduced by Anthropic for connecting LLMs to tools, data sources, and prompts in a portable way. Think of it as USB-C for AI integrations.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    relations: [
      { targetId: 'function-calling', type: RelationType.ALTERNATIVE_TO },
      { targetId: 'claude-code', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'prompt-engineering',
    name: 'Prompt Engineering',
    category: ToolCategory.CONCEPT,
    description: "The craft of writing instructions to get the best output from an LLM. Small changes in wording can dramatically change quality, cost, and reliability.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
  },
  {
    id: 'chain-of-thought',
    name: 'Chain of Thought (CoT)',
    category: ToolCategory.CONCEPT,
    description: 'Asking the model to "think step by step" before answering. Usually massively improves accuracy on math, logic, and multi-step reasoning tasks.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
  },
  {
    id: 'multimodal',
    name: 'Multimodal AI',
    category: ToolCategory.CONCEPT,
    description: "Models that handle multiple input types — text, images, audio, video — natively in one system. GPT-5, Claude 4, and Gemini 2.5 are all multimodal.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
  },
  {
    id: 'fine-tuning',
    name: 'Fine-tuning',
    category: ToolCategory.CONCEPT,
    description: 'Training an existing model on your own data to specialize it for a domain or style. Fine-tuning is for changing behavior; RAG is for adding knowledge.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.PAID,
    relations: [
      { targetId: 'lora', type: RelationType.IMPLEMENTS },
    ],
  },
  {
    id: 'prompt-caching',
    name: 'Prompt Caching',
    category: ToolCategory.CONCEPT,
    description: 'Reusing expensive context (system prompts, large docs) across requests at a steep discount. The single biggest cost-cutting technique for production AI apps.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
  },
  {
    id: 'context-window',
    name: 'Context Window',
    category: ToolCategory.CONCEPT,
    description: "The max amount of text an LLM can 'see' at once, measured in tokens. Modern frontier models support 200k–2M tokens, but cost scales with what you send.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
  },
  {
    id: 'hallucination',
    name: 'Hallucination',
    category: ToolCategory.CONCEPT,
    description: 'When an LLM confidently states something false. The #1 reliability problem in AI apps — RAG, tool use, and verification chains are common mitigations.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
  },
  {
    id: 'guardrails',
    name: 'Guardrails / AI Safety',
    category: ToolCategory.CONCEPT,
    description: 'Layers that constrain LLM outputs — blocking harmful content, validating schemas, redacting PII, enforcing tone. Required for any user-facing AI product.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
  },
  {
    id: 'lora',
    name: 'LoRA (Low-Rank Adaptation)',
    category: ToolCategory.CONCEPT,
    description: 'A parameter-efficient fine-tuning technique. Train a small "adapter" instead of the whole model — 1000x cheaper, comparable results for most tasks.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
  },
  {
    id: 'streaming',
    name: 'Streaming',
    category: ToolCategory.CONCEPT,
    description: 'Returning the LLM response token-by-token as it generates instead of waiting for the full output. Standard UX for chat apps — feels 10x faster.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
  },

  // ============================================================
  // LANGUAGE MODELS (frontier, 2026)
  // ============================================================
  {
    id: 'claude-opus-4-7',
    name: 'Claude Opus 4.7',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "Anthropic's flagship reasoning model. Best-in-class for complex agentic tasks, coding, and structured output. Slow and pricey but extremely capable.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://www.anthropic.com/claude',
    relations: [
      { targetId: 'claude-sonnet-4-6', type: RelationType.ALTERNATIVE_TO },
      { targetId: 'gpt-5', type: RelationType.ALTERNATIVE_TO },
    ],
  },
  {
    id: 'claude-sonnet-4-6',
    name: 'Claude Sonnet 4.6',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "Anthropic's balanced workhorse. Frontier-level reasoning at a fraction of Opus's price. The default pick for most production AI features.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://www.anthropic.com/claude',
  },
  {
    id: 'claude-haiku-4-5',
    name: 'Claude Haiku 4.5',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "Anthropic's fastest, cheapest tier. Smarter than last-gen flagships at a fraction of the cost — ideal for high-volume tasks like classification and tool routing.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://www.anthropic.com/claude',
  },
  {
    id: 'gpt-5',
    name: 'OpenAI GPT-5',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "OpenAI's frontier flagship. Strong all-rounder with native multimodal input/output and built-in reasoning. The Microsoft-backed default.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://platform.openai.com',
    relations: [
      { targetId: 'claude-opus-4-7', type: RelationType.ALTERNATIVE_TO },
    ],
  },
  {
    id: 'gpt-5-mini',
    name: 'OpenAI GPT-5 Mini',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "OpenAI's cheap-and-fast tier. Great for chat, classification, and summarization where you don't need reasoning depth.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://platform.openai.com',
  },
  {
    id: 'openai-o3',
    name: 'OpenAI o3',
    category: ToolCategory.LANGUAGE_MODEL,
    description: 'Specialized reasoning model that "thinks" before answering. Best for math, code, science, and any problem where slow-but-correct beats fast.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://platform.openai.com',
  },
  {
    id: 'gemini-2-5-pro',
    name: 'Google Gemini 2.5 Pro',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "Google's flagship with the longest context window in the industry (1M+ tokens) and native multimodal everything. Best when you need to dump huge documents in.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://ai.google.dev',
  },
  {
    id: 'gemini-2-5-flash',
    name: 'Google Gemini 2.5 Flash',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "Google's cheap workhorse with the same massive context window. The most cost-efficient frontier model on the market for long-document tasks.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://ai.google.dev',
  },
  {
    id: 'llama-4',
    name: 'Meta Llama 4',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "Meta's open-weights frontier model. Run it yourself, fine-tune freely, or host through any inference provider. The benchmark for open AI.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://llama.meta.com',
    relations: [
      { targetId: 'groq', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'together-ai', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'mistral-large-3',
    name: 'Mistral Large 3',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "France's frontier offering. Strong code and multilingual performance, competitive pricing, EU-hosted — popular for European compliance use cases.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://mistral.ai',
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek-R1',
    category: ToolCategory.LANGUAGE_MODEL,
    description: 'Open-weights reasoning model from DeepSeek. Comparable to o3 on math and code benchmarks at a tiny fraction of the inference cost.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://www.deepseek.com',
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek-V3',
    category: ToolCategory.LANGUAGE_MODEL,
    description: 'High-performance open-weights MoE model. Excellent quality-per-dollar, often the choice for self-hosted production deployments.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://www.deepseek.com',
  },
  {
    id: 'qwen-3',
    name: 'Alibaba Qwen 3',
    category: ToolCategory.LANGUAGE_MODEL,
    description: 'Open-weights flagship from Alibaba. Strong on code and Chinese-language tasks, competitive on English benchmarks.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://qwenlm.ai',
  },
  {
    id: 'grok-4',
    name: 'xAI Grok 4',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "Elon Musk's xAI model with built-in web/X search. Real-time information without separate retrieval plumbing.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://x.ai',
  },
  {
    id: 'command-r-plus',
    name: 'Cohere Command R+',
    category: ToolCategory.LANGUAGE_MODEL,
    description: 'Enterprise-focused LLM with native RAG and tool-use grounding. Strong choice when you need citations and traceability for compliance.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://cohere.com',
  },
  {
    id: 'phi-4',
    name: 'Microsoft Phi-4',
    category: ToolCategory.LANGUAGE_MODEL,
    description: 'Small (~14B params) but punchy open-weights model from Microsoft Research. Great for on-device and edge deployments.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://huggingface.co/microsoft',
  },
  {
    id: 'amazon-nova',
    name: 'Amazon Nova',
    category: ToolCategory.LANGUAGE_MODEL,
    description: "Amazon's family of multimodal models on AWS Bedrock. Tightly integrated with the AWS stack and competitively priced.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://aws.amazon.com/bedrock',
    relations: [
      { targetId: 'aws-bedrock', type: RelationType.WORKS_BEST_WITH },
    ],
  },

  // ============================================================
  // CODE ASSISTANTS
  // ============================================================
  {
    id: 'claude-code',
    name: 'Claude Code',
    category: ToolCategory.CODE_ASSISTANT,
    description: "Anthropic's official terminal-native coding agent. Reads, writes, and runs code across your repo with deep MCP and tool-use support. Pairs with Claude Opus/Sonnet.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://claude.com/code',
    relations: [
      { targetId: 'claude-opus-4-7', type: RelationType.DEPENDS_ON },
      { targetId: 'mcp', type: RelationType.IMPLEMENTS },
    ],
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Microsoft/GitHub coding assistant with inline completions, chat, and PR review. Deep VS Code and JetBrains integration. The most-deployed AI tool in industry.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://github.com/features/copilot',
  },
  {
    id: 'cursor',
    name: 'Cursor',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'AI-first VS Code fork. Strong agent mode, multi-file edits, codebase-wide context. The most popular alternative to Copilot.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://cursor.com',
  },
  {
    id: 'windsurf',
    name: 'Windsurf',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Codeium\'s AI-first IDE. "Cascade" agent flow with deep codebase awareness and MCP support. Free tier is unusually generous.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://codeium.com/windsurf',
  },
  {
    id: 'cline',
    name: 'Cline',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Open-source VS Code agent extension. Bring your own model (Claude, GPT, Gemini, local). Strong for users who want full control.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://cline.bot',
  },
  {
    id: 'aider',
    name: 'Aider',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Terminal-based AI pair programmer. Git-aware: every change becomes a clean commit. Beloved by CLI-first developers.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://aider.chat',
  },
  {
    id: 'continue',
    name: 'Continue',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Open-source IDE assistant for VS Code and JetBrains. Pluggable model layer, custom slash commands, local-first option.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://continue.dev',
  },
  {
    id: 'codeium',
    name: 'Codeium',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Free AI completions across 70+ editors. Free tier is unlimited for individuals — popular among hobbyists and OSS contributors.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://codeium.com',
  },
  {
    id: 'devin',
    name: 'Devin',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Cognition Labs autonomous SWE agent. Plans, codes, tests, and ships features end-to-end. Premium-priced, async-first.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://devin.ai',
  },
  {
    id: 'replit-agent',
    name: 'Replit Agent',
    category: ToolCategory.CODE_ASSISTANT,
    description: "Replit's browser-based AI builder. Describe an app, watch it scaffold and deploy. Best for prototypes and low-config web apps.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://replit.com',
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Enterprise-focused code completion with on-prem and air-gapped deployment options. Popular in regulated industries.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.tabnine.com',
  },
  {
    id: 'sweep',
    name: 'Sweep',
    category: ToolCategory.CODE_ASSISTANT,
    description: 'Issue-to-PR agent. Tag it on a GitHub issue, it opens a PR with the fix. Best for backlog grooming and small bug fixes.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://sweep.dev',
  },

  // ============================================================
  // IMAGE GENERATION
  // ============================================================
  {
    id: 'midjourney',
    name: 'Midjourney v7',
    category: ToolCategory.IMAGE_GENERATION,
    description: 'The aesthetic gold standard. Best for stylized artistic output, illustration, and brand concepts. Web app + Discord.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://www.midjourney.com',
  },
  {
    id: 'flux-pro',
    name: 'Flux 1.1 Pro',
    category: ToolCategory.IMAGE_GENERATION,
    description: 'Black Forest Labs flagship. Photorealism leader with the strongest prompt adherence in the industry. Available via API.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://blackforestlabs.ai',
    relations: [
      { targetId: 'replicate', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'dall-e-3',
    name: 'DALL-E 3',
    category: ToolCategory.IMAGE_GENERATION,
    description: "OpenAI's image model, baked into ChatGPT and the API. Strong text rendering and prompt understanding. Easiest to integrate.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://openai.com/dall-e-3',
  },
  {
    id: 'ideogram',
    name: 'Ideogram 2',
    category: ToolCategory.IMAGE_GENERATION,
    description: 'Best-in-class for in-image text rendering — logos, posters, signs. The choice for marketing assets.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://ideogram.ai',
  },
  {
    id: 'stable-diffusion-3-5',
    name: 'Stable Diffusion 3.5',
    category: ToolCategory.IMAGE_GENERATION,
    description: 'Open-weights image model from Stability AI. Run it yourself, fine-tune for your style, full creative control.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://stability.ai',
  },
  {
    id: 'recraft',
    name: 'Recraft V3',
    category: ToolCategory.IMAGE_GENERATION,
    description: 'Designer-focused image AI with brand style consistency, vector output, and a built-in asset library.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.recraft.ai',
  },
  {
    id: 'krea',
    name: 'Krea',
    category: ToolCategory.IMAGE_GENERATION,
    description: 'Real-time generation with live drawing, image-to-image, and video. The fastest creative iteration loop on the market.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.krea.ai',
  },
  {
    id: 'playground',
    name: 'Playground AI',
    category: ToolCategory.IMAGE_GENERATION,
    description: 'Browser-based image generation with a simple UI and aggressive free tier. Great entry point for non-developers.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://playground.com',
  },

  // ============================================================
  // VIDEO GENERATION
  // ============================================================
  {
    id: 'sora-2',
    name: 'OpenAI Sora 2',
    category: ToolCategory.VIDEO_GENERATION,
    description: "OpenAI's video model. Best-in-class motion realism and 60-second-plus clips. Available via ChatGPT Pro and the API.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://openai.com/sora',
  },
  {
    id: 'runway-gen-4',
    name: 'Runway Gen-4',
    category: ToolCategory.VIDEO_GENERATION,
    description: 'Filmmaker-favorite tooling: image-to-video, video-to-video, motion brush, character consistency. Used in actual TV and film production.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://runwayml.com',
  },
  {
    id: 'veo-3',
    name: 'Google Veo 3',
    category: ToolCategory.VIDEO_GENERATION,
    description: "Google DeepMind's frontier video model. Native audio generation alongside video — voice, music, ambient sound. Available via Vertex AI.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://deepmind.google/technologies/veo',
  },
  {
    id: 'kling-2',
    name: 'Kling 2',
    category: ToolCategory.VIDEO_GENERATION,
    description: "Kuaishou's video model. Excellent physics simulation and camera control. Strong contender to Sora at lower cost.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://klingai.com',
  },
  {
    id: 'pika',
    name: 'Pika 2',
    category: ToolCategory.VIDEO_GENERATION,
    description: 'Consumer-friendly video creation with strong template library. Great for social media content.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://pika.art',
  },
  {
    id: 'luma-dream-machine',
    name: 'Luma Dream Machine',
    category: ToolCategory.VIDEO_GENERATION,
    description: "Luma Labs' video AI. Strong on photorealism and natural motion. Has a free tier suitable for experimentation.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://lumalabs.ai',
  },
  {
    id: 'hailuo',
    name: 'Hailuo (MiniMax)',
    category: ToolCategory.VIDEO_GENERATION,
    description: "MiniMax's video model. Notable for character consistency and cinematic camera moves. Free tier available.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://hailuoai.video',
  },
  {
    id: 'heygen',
    name: 'HeyGen',
    category: ToolCategory.VIDEO_GENERATION,
    description: 'AI avatar video — talking-head presenters from a script. Most-used in marketing, training, and localization.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.PAID,
    website: 'https://www.heygen.com',
  },

  // ============================================================
  // FRAMEWORKS
  // ============================================================
  {
    id: 'langchain',
    name: 'LangChain',
    category: ToolCategory.FRAMEWORK,
    description: 'The most popular Python/TS framework for building LLM apps. Heavyweight but covers everything: chains, retrievers, agents, integrations.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://www.langchain.com',
    relations: [
      { targetId: 'pinecone', type: RelationType.INTEGRATES_WITH },
      { targetId: 'chroma', type: RelationType.INTEGRATES_WITH },
      { targetId: 'langsmith', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'langgraph', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'llama-index',
    name: 'LlamaIndex',
    category: ToolCategory.FRAMEWORK,
    description: 'RAG-first framework. Excels at document ingestion, indexing, and retrieval. Lighter than LangChain when you mostly need RAG.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://www.llamaindex.ai',
    relations: [
      { targetId: 'rag', type: RelationType.IMPLEMENTS },
      { targetId: 'langchain', type: RelationType.ALTERNATIVE_TO },
    ],
  },
  {
    id: 'vercel-ai-sdk',
    name: 'Vercel AI SDK',
    category: ToolCategory.FRAMEWORK,
    description: "Vercel's TypeScript-first toolkit for streaming, structured outputs, tool use, and React UI. The default for Next.js AI apps.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://ai-sdk.dev',
    relations: [
      { targetId: 'nextjs', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'streaming', type: RelationType.IMPLEMENTS },
    ],
  },
  {
    id: 'langgraph',
    name: 'LangGraph',
    category: ToolCategory.FRAMEWORK,
    description: "LangChain's agent runtime. Build stateful, multi-actor agents as a directed graph. The serious tool for production agentic systems.",
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    website: 'https://www.langchain.com/langgraph',
    relations: [
      { targetId: 'langchain', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'agentic-ai', type: RelationType.IMPLEMENTS },
    ],
  },
  {
    id: 'dspy',
    name: 'DSPy',
    category: ToolCategory.FRAMEWORK,
    description: 'Stanford framework that "compiles" prompts. Optimize prompts and few-shot examples programmatically instead of hand-tuning.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    website: 'https://dspy.ai',
  },
  {
    id: 'pydantic-ai',
    name: 'Pydantic AI',
    category: ToolCategory.FRAMEWORK,
    description: "Pydantic's typed LLM framework. Schema-first, FastAPI-style ergonomics. Great choice for Python-first AI APIs.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://ai.pydantic.dev',
  },
  {
    id: 'mastra',
    name: 'Mastra',
    category: ToolCategory.FRAMEWORK,
    description: 'TypeScript agent framework — workflows, memory, RAG, evals — all batteries-included. Built by the Gatsby founders.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://mastra.ai',
  },
  {
    id: 'genkit',
    name: 'Firebase Genkit',
    category: ToolCategory.FRAMEWORK,
    description: "Google's open-source AI app framework for Node.js, Go, and Python. First-class on Google Cloud and Firebase.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://firebase.google.com/products/genkit',
  },
  {
    id: 'haystack',
    name: 'Haystack',
    category: ToolCategory.FRAMEWORK,
    description: "deepset's production-grade RAG and search framework. Modular pipelines, strong observability, mature deployment story.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://haystack.deepset.ai',
  },
  {
    id: 'semantic-kernel',
    name: 'Semantic Kernel',
    category: ToolCategory.FRAMEWORK,
    description: "Microsoft's open-source SDK for blending AI with conventional code. Strong .NET support; cross-language.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://github.com/microsoft/semantic-kernel',
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    category: ToolCategory.FRAMEWORK,
    description: "Vercel's React framework. App Router, server components, edge runtime — the de facto choice for AI-powered web apps.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://nextjs.org',
    relations: [
      { targetId: 'vercel', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'vercel-ai-sdk', type: RelationType.WORKS_BEST_WITH },
    ],
  },

  // ============================================================
  // AGENT ORCHESTRATION
  // ============================================================
  {
    id: 'crew-ai',
    name: 'CrewAI',
    category: ToolCategory.AGENT_ORCHESTRATION,
    description: 'Role-based agent framework — define a "crew" of specialized agents that collaborate on a task. Pythonic and approachable.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://www.crewai.com',
    relations: [
      { targetId: 'agentic-ai', type: RelationType.IMPLEMENTS },
    ],
  },
  {
    id: 'autogen',
    name: 'AutoGen',
    category: ToolCategory.AGENT_ORCHESTRATION,
    description: "Microsoft's multi-agent conversation framework. Agents talk to each other to solve problems. Strong research community.",
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    website: 'https://microsoft.github.io/autogen',
  },
  {
    id: 'openai-swarm',
    name: 'OpenAI Swarm',
    category: ToolCategory.AGENT_ORCHESTRATION,
    description: "OpenAI's lightweight handoff-style multi-agent pattern. Small, readable, official reference implementation.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://github.com/openai/swarm',
  },
  {
    id: 'ag2',
    name: 'AG2',
    category: ToolCategory.AGENT_ORCHESTRATION,
    description: 'Community-driven successor to AutoGen 0.2. More flexible than the upstream rewrite, broader integration set.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    website: 'https://ag2.ai',
  },
  {
    id: 'trigger-dev',
    name: 'Trigger.dev',
    category: ToolCategory.AGENT_ORCHESTRATION,
    description: 'Long-running background jobs and AI workflows in TypeScript. Solves the "my agent runs for 30 minutes" deployment problem.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://trigger.dev',
  },

  // ============================================================
  // VECTOR DATABASES
  // ============================================================
  {
    id: 'pinecone',
    name: 'Pinecone',
    category: ToolCategory.VECTOR_DATABASE,
    description: 'Managed vector DB pioneer. Zero-ops, scales to billions of vectors, popular in enterprise RAG deployments.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.pinecone.io',
    relations: [
      { targetId: 'rag', type: RelationType.IMPLEMENTS },
    ],
  },
  {
    id: 'chroma',
    name: 'Chroma',
    category: ToolCategory.VECTOR_DATABASE,
    description: 'Open-source vector DB with a friendly Python API. Embedded mode for prototypes, cloud mode for production.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.trychroma.com',
  },
  {
    id: 'weaviate',
    name: 'Weaviate',
    category: ToolCategory.VECTOR_DATABASE,
    description: 'Open-source vector DB with hybrid search (vector + keyword), built-in modules for embeddings and rerankers.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://weaviate.io',
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    category: ToolCategory.VECTOR_DATABASE,
    description: 'Rust-powered open-source vector DB. Fast, reliable, cleanly designed payload filtering — popular for self-hosted deploys.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://qdrant.tech',
  },
  {
    id: 'milvus',
    name: 'Milvus',
    category: ToolCategory.VECTOR_DATABASE,
    description: 'CNCF-graduated open-source vector DB. Battle-tested at scale (trillions of vectors). Heavyweight, ops-intensive.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    website: 'https://milvus.io',
  },
  {
    id: 'pgvector',
    name: 'pgvector',
    category: ToolCategory.VECTOR_DATABASE,
    description: 'Postgres extension that adds vector search. The pragmatic choice if you already run Postgres — no extra service to operate.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://github.com/pgvector/pgvector',
    relations: [
      { targetId: 'postgresql', type: RelationType.DEPENDS_ON },
      { targetId: 'supabase', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'lance-db',
    name: 'LanceDB',
    category: ToolCategory.VECTOR_DATABASE,
    description: 'Embedded, serverless vector DB with a columnar file format. Ideal for local-first AI apps and edge deployments.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://lancedb.com',
  },

  // ============================================================
  // AI OBSERVABILITY
  // ============================================================
  {
    id: 'langsmith',
    name: 'LangSmith',
    category: ToolCategory.AI_OBSERVABILITY,
    description: 'LangChain\'s observability and evaluation platform. Trace every LLM call, debug prompts, run evals. The default for LangChain users.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.langchain.com/langsmith',
    relations: [
      { targetId: 'langchain', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'helicone',
    name: 'Helicone',
    category: ToolCategory.AI_OBSERVABILITY,
    description: 'One-line proxy for LLM observability. Logs, costs, caching, rate limiting — minimal integration effort.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.helicone.ai',
  },
  {
    id: 'langfuse',
    name: 'Langfuse',
    category: ToolCategory.AI_OBSERVABILITY,
    description: 'Open-source LLM observability with self-hosted option. Tracing, evals, prompt management, A/B testing.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://langfuse.com',
  },
  {
    id: 'braintrust',
    name: 'Braintrust',
    category: ToolCategory.AI_OBSERVABILITY,
    description: 'Eval-first observability. Grade outputs, regression-test prompts, ship with confidence. Beloved by ML engineers.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.braintrust.dev',
  },
  {
    id: 'phoenix-arize',
    name: 'Arize Phoenix',
    category: ToolCategory.AI_OBSERVABILITY,
    description: 'Open-source LLM tracing built on OpenTelemetry. Self-hosted, works alongside existing APM stacks.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://phoenix.arize.com',
  },
  {
    id: 'comet-opik',
    name: 'Comet Opik',
    category: ToolCategory.AI_OBSERVABILITY,
    description: 'Open-source LLM evaluation and monitoring from Comet. Strong on annotation and human-in-the-loop workflows.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.comet.com/site/products/opik',
  },
  {
    id: 'datadog-llm',
    name: 'Datadog LLM Observability',
    category: ToolCategory.AI_OBSERVABILITY,
    description: "Datadog's LLM monitoring add-on. The right choice if your observability stack is already Datadog.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://www.datadoghq.com/product/llm-observability',
  },

  // ============================================================
  // AI INFERENCE
  // ============================================================
  {
    id: 'groq',
    name: 'Groq',
    category: ToolCategory.AI_INFERENCE,
    description: 'Custom LPU silicon for hyper-fast inference. 500+ tokens/sec on Llama and Mixtral. Best when latency matters.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://groq.com',
    relations: [
      { targetId: 'llama-4', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: ToolCategory.AI_INFERENCE,
    description: 'Run any open-source model with one API call. Great for image, audio, video models — pay-per-second.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://replicate.com',
  },
  {
    id: 'together-ai',
    name: 'Together AI',
    category: ToolCategory.AI_INFERENCE,
    description: 'Inference for 100+ open-source models with OpenAI-compatible APIs. Strong fine-tuning offering.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.together.ai',
  },
  {
    id: 'fireworks-ai',
    name: 'Fireworks AI',
    category: ToolCategory.AI_INFERENCE,
    description: 'Speed-optimized inference for open-source models. Strong on function-calling and structured output.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://fireworks.ai',
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    category: ToolCategory.AI_INFERENCE,
    description: 'Wafer-scale chips for the absolute fastest LLM inference. 1000+ tokens/sec on Llama models. Premium tier.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://cerebras.ai',
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock',
    category: ToolCategory.AI_INFERENCE,
    description: 'Amazon\'s managed LLM marketplace — Claude, Llama, Titan, Mistral, Cohere all behind one IAM-controlled API.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://aws.amazon.com/bedrock',
    relations: [
      { targetId: 'aws', type: RelationType.DEPENDS_ON },
    ],
  },
  {
    id: 'azure-ai-foundry',
    name: 'Azure AI Foundry',
    category: ToolCategory.AI_INFERENCE,
    description: "Microsoft's enterprise AI platform. OpenAI models with Azure compliance, plus a model catalog and tooling.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://ai.azure.com',
    relations: [
      { targetId: 'azure', type: RelationType.DEPENDS_ON },
    ],
  },
  {
    id: 'modal',
    name: 'Modal',
    category: ToolCategory.AI_INFERENCE,
    description: 'Serverless GPU compute. Decorator-based Python — turn any function into a scalable inference endpoint.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://modal.com',
  },
  {
    id: 'cloudflare-workers-ai',
    name: 'Cloudflare Workers AI',
    category: ToolCategory.AI_INFERENCE,
    description: "Cloudflare's edge inference. Run Llama, Mistral, Whisper, and SD at the edge near your users. No cold starts.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://developers.cloudflare.com/workers-ai',
    relations: [
      { targetId: 'cloudflare', type: RelationType.DEPENDS_ON },
    ],
  },

  // ============================================================
  // DATA INGESTION
  // ============================================================
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: ToolCategory.DATA_INGESTION,
    description: 'Turn any website into clean, LLM-ready markdown. Handles JS-heavy sites, sitemaps, and structured extraction.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.firecrawl.dev',
  },
  {
    id: 'unstructured-io',
    name: 'Unstructured',
    category: ToolCategory.DATA_INGESTION,
    description: 'Parse PDFs, Word docs, PowerPoint, HTML, emails — into structured chunks ready for RAG. The de-facto preprocessor.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://unstructured.io',
  },
  {
    id: 'llama-parse',
    name: 'LlamaParse',
    category: ToolCategory.DATA_INGESTION,
    description: "LlamaIndex's premium PDF/document parser. Best-in-class for complex layouts — tables, diagrams, footnotes.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.llamaindex.ai/llamaparse',
  },
  {
    id: 'reducto',
    name: 'Reducto',
    category: ToolCategory.DATA_INGESTION,
    description: 'Vision-LLM document parsing. Highest fidelity on tables and forms. Premium pricing, premium accuracy.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://reducto.ai',
  },
  {
    id: 'apify',
    name: 'Apify',
    category: ToolCategory.DATA_INGESTION,
    description: 'Web scraping platform with a marketplace of pre-built actors (LinkedIn, Twitter, Google Maps, etc.).',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://apify.com',
  },
  {
    id: 'bright-data',
    name: 'Bright Data',
    category: ToolCategory.DATA_INGESTION,
    description: 'Enterprise web data infrastructure — proxies, scraping, datasets. The pick when you need scale and reliability.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.PAID,
    website: 'https://brightdata.com',
  },
  {
    id: 'scrapingbee',
    name: 'ScrapingBee',
    category: ToolCategory.DATA_INGESTION,
    description: 'Simple scraping API that handles JS rendering and proxy rotation. Pay-per-request.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.scrapingbee.com',
  },

  // ============================================================
  // DATA SCIENCE
  // ============================================================
  {
    id: 'hugging-face',
    name: 'Hugging Face',
    category: ToolCategory.DATA_SCIENCE,
    description: 'The GitHub of AI. 1M+ open models, datasets, Spaces (gradio demos), inference endpoints. Indispensable.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://huggingface.co',
  },
  {
    id: 'pandas',
    name: 'Pandas',
    category: ToolCategory.DATA_SCIENCE,
    description: "Python's de-facto dataframe library. The first stop for anyone exploring or cleaning tabular data.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://pandas.pydata.org',
  },
  {
    id: 'numpy',
    name: 'NumPy',
    category: ToolCategory.DATA_SCIENCE,
    description: 'Foundational numerical Python — N-dim arrays, linear algebra, FFTs. Almost every other ML library is built on top.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://numpy.org',
  },
  {
    id: 'jupyter',
    name: 'Jupyter',
    category: ToolCategory.DATA_SCIENCE,
    description: 'Notebook environment for interactive data exploration. The default surface for ML research and tutorials.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://jupyter.org',
  },
  {
    id: 'scikit-learn',
    name: 'scikit-learn',
    category: ToolCategory.DATA_SCIENCE,
    description: 'Classical ML in Python — regression, clustering, decision trees, the lot. Still the right tool for non-deep-learning problems.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://scikit-learn.org',
  },
  {
    id: 'pytorch',
    name: 'PyTorch',
    category: ToolCategory.DATA_SCIENCE,
    description: 'The dominant deep learning framework. Powers most modern open-source LLMs and research code.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    website: 'https://pytorch.org',
  },
  {
    id: 'tensorflow',
    name: 'TensorFlow',
    category: ToolCategory.DATA_SCIENCE,
    description: "Google's deep learning framework. Lost ground to PyTorch in research; still common in mobile/edge deployments.",
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    website: 'https://www.tensorflow.org',
  },
  {
    id: 'polars',
    name: 'Polars',
    category: ToolCategory.DATA_SCIENCE,
    description: 'Rust-powered DataFrame library — 10–100x faster than pandas on big data. The modern replacement.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://pola.rs',
  },

  // ============================================================
  // DATABASE
  // ============================================================
  {
    id: 'supabase',
    name: 'Supabase',
    category: ToolCategory.DATABASE,
    description: 'Postgres-as-a-service with auth, storage, and built-in pgvector. The Firebase alternative for the AI era.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://supabase.com',
    relations: [
      { targetId: 'pgvector', type: RelationType.INTEGRATES_WITH },
      { targetId: 'postgresql', type: RelationType.IMPLEMENTS },
    ],
  },
  {
    id: 'postgresql',
    name: 'PostgreSQL',
    category: ToolCategory.DATABASE,
    description: 'The most-loved SQL database. Open-source, rock-solid, infinitely extensible (pgvector, pgmq, ...). Your default DB.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://www.postgresql.org',
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: ToolCategory.DATABASE,
    description: 'Document database with built-in Atlas Vector Search. Popular in JS/TS stacks for flexible schemas.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.mongodb.com',
  },
  {
    id: 'neon',
    name: 'Neon',
    category: ToolCategory.DATABASE,
    description: 'Serverless Postgres — branching, autoscaling, scale-to-zero. Pgvector built in. Great for AI app prototypes.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://neon.tech',
  },
  {
    id: 'turso',
    name: 'Turso',
    category: ToolCategory.DATABASE,
    description: 'Edge SQLite (libSQL). Replicas at the edge for ultra-low latency reads. Built-in vector search.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://turso.tech',
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    category: ToolCategory.DATABASE,
    description: 'Managed MySQL with branching. Strong CI/CD integration, used by many high-scale SaaS products.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://planetscale.com',
  },
  {
    id: 'convex',
    name: 'Convex',
    category: ToolCategory.DATABASE,
    description: 'Reactive backend-as-a-service in TypeScript. Realtime queries, scheduled functions, vector search built in.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://convex.dev',
  },

  // ============================================================
  // API DEVELOPMENT
  // ============================================================
  {
    id: 'fastapi',
    name: 'FastAPI',
    category: ToolCategory.API_DEVELOPMENT,
    description: "Python's modern web framework. Type-hints + automatic docs + async — the default for ML/AI APIs.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://fastapi.tiangolo.com',
  },
  {
    id: 'express',
    name: 'Express.js',
    category: ToolCategory.API_DEVELOPMENT,
    description: "Node's classic minimalist web framework. Battle-tested, huge ecosystem, fine for most JS APIs.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://expressjs.com',
  },
  {
    id: 'fastify',
    name: 'Fastify',
    category: ToolCategory.API_DEVELOPMENT,
    description: "Express's faster, more modern successor. Schema-first, great TypeScript story, low overhead.",
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://fastify.dev',
  },
  {
    id: 'hono',
    name: 'Hono',
    category: ToolCategory.API_DEVELOPMENT,
    description: 'Ultrafast edge-first web framework. Runs on Cloudflare Workers, Deno, Bun, Lambda. Tiny footprint.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://hono.dev',
  },
  {
    id: 'trpc',
    name: 'tRPC',
    category: ToolCategory.API_DEVELOPMENT,
    description: 'End-to-end typesafe APIs without codegen. Loved in Next.js + Prisma stacks for monorepos.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREE,
    website: 'https://trpc.io',
  },

  // ============================================================
  // VERSION CONTROL
  // ============================================================
  {
    id: 'git',
    name: 'Git',
    category: ToolCategory.VERSION_CONTROL,
    description: "The distributed version control system every developer needs. There's no good alternative.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREE,
    website: 'https://git-scm.com',
  },
  {
    id: 'github',
    name: 'GitHub',
    category: ToolCategory.VERSION_CONTROL,
    description: "Code hosting + Actions + Copilot + Codespaces. Microsoft-owned and the world's default code platform.",
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://github.com',
  },

  // ============================================================
  // CONTAINERIZATION
  // ============================================================
  {
    id: 'docker',
    name: 'Docker',
    category: ToolCategory.CONTAINERIZATION,
    description: 'Containerize any app — package code, deps, and runtime into a portable image. The bedrock of modern deployment.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.docker.com',
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    category: ToolCategory.CONTAINERIZATION,
    description: 'Container orchestration at scale. Powerful, complex — only worth it past a certain size and ops budget.',
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.FREE,
    website: 'https://kubernetes.io',
  },

  // ============================================================
  // CI/CD
  // ============================================================
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    category: ToolCategory.CI_CD,
    description: 'CI/CD baked into GitHub. YAML workflows, huge marketplace of pre-built actions. Free for public repos.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://github.com/features/actions',
    relations: [
      { targetId: 'github', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    category: ToolCategory.CI_CD,
    description: 'Mature standalone CI/CD platform. Strong on parallelization, complex workflows, and self-hosted runners.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://circleci.com',
  },

  // ============================================================
  // CLOUD PLATFORM
  // ============================================================
  {
    id: 'aws',
    name: 'AWS',
    category: ToolCategory.CLOUD_PLATFORM,
    description: "Amazon Web Services. The biggest cloud — every service you'd ever need, but a learning curve to match.",
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.PAID,
    website: 'https://aws.amazon.com',
  },
  {
    id: 'gcp',
    name: 'Google Cloud',
    category: ToolCategory.CLOUD_PLATFORM,
    description: "Google's cloud. Strong on data/ML (BigQuery, Vertex AI) and Kubernetes. Best price-performance for ML workloads.",
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.PAID,
    website: 'https://cloud.google.com',
  },
  {
    id: 'azure',
    name: 'Microsoft Azure',
    category: ToolCategory.CLOUD_PLATFORM,
    description: "Microsoft's cloud. Default for enterprises with Microsoft contracts. Tightest OpenAI integration.",
    difficulty: Difficulty.ADVANCED,
    pricing: Pricing.PAID,
    website: 'https://azure.microsoft.com',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    category: ToolCategory.CLOUD_PLATFORM,
    description: 'Edge platform — Workers, Pages, R2, D1, Workers AI. Generous free tier; the most developer-friendly cloud.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.cloudflare.com',
  },

  // ============================================================
  // DEPLOYMENT
  // ============================================================
  {
    id: 'vercel',
    name: 'Vercel',
    category: ToolCategory.DEPLOYMENT,
    description: 'Frontend platform built around Next.js. Git push to production, edge functions, AI SDK integration. The fastest path to prod for web AI.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://vercel.com',
    relations: [
      { targetId: 'nextjs', type: RelationType.WORKS_BEST_WITH },
      { targetId: 'vercel-ai-sdk', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'cloudflare-pages',
    name: 'Cloudflare Pages',
    category: ToolCategory.DEPLOYMENT,
    description: 'Static + serverless functions on the Cloudflare edge. Free tier covers most projects; pairs well with Workers AI.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://pages.cloudflare.com',
    relations: [
      { targetId: 'cloudflare', type: RelationType.DEPENDS_ON },
      { targetId: 'cloudflare-workers-ai', type: RelationType.WORKS_BEST_WITH },
    ],
  },
  {
    id: 'netlify',
    name: 'Netlify',
    category: ToolCategory.DEPLOYMENT,
    description: 'OG of frontend deploys. Forms, identity, Edge Functions. Strong for static sites and JAMstack apps.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.netlify.com',
  },
  {
    id: 'railway',
    name: 'Railway',
    category: ToolCategory.DEPLOYMENT,
    description: 'Full-stack PaaS — backends, databases, cron, all in one place. Heroku for the modern era.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://railway.app',
  },
  {
    id: 'fly-io',
    name: 'Fly.io',
    category: ToolCategory.DEPLOYMENT,
    description: 'Run Docker containers across global regions. Strong for stateful apps and SQLite-replicated workloads.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://fly.io',
  },
  {
    id: 'render',
    name: 'Render',
    category: ToolCategory.DEPLOYMENT,
    description: 'Heroku-style PaaS — web services, cron, Postgres, Redis. Predictable pricing, simple UX.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://render.com',
  },

  // ============================================================
  // MONITORING
  // ============================================================
  {
    id: 'sentry',
    name: 'Sentry',
    category: ToolCategory.MONITORING,
    description: 'Error tracking and performance monitoring. Drop in a SDK, get every exception in production. Standard.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://sentry.io',
  },
  {
    id: 'datadog',
    name: 'Datadog',
    category: ToolCategory.MONITORING,
    description: 'Enterprise APM, infrastructure, logs, and synthetic monitoring. Expensive but comprehensive.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.PAID,
    website: 'https://www.datadoghq.com',
  },
  {
    id: 'posthog',
    name: 'PostHog',
    category: ToolCategory.MONITORING,
    description: 'Open-source product analytics + session replay + feature flags + A/B tests. Self-hostable, AI-native.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://posthog.com',
  },

  // ============================================================
  // PROJECT MANAGEMENT
  // ============================================================
  {
    id: 'linear',
    name: 'Linear',
    category: ToolCategory.PROJECT_MANAGEMENT,
    description: 'Issue tracking that engineers actually like. Fast, opinionated, keyboard-first. The Jira replacement everyone wants.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://linear.app',
  },
  {
    id: 'notion',
    name: 'Notion',
    category: ToolCategory.PROJECT_MANAGEMENT,
    description: 'Docs + databases + project tracking + AI. Great team wiki and lightweight project management.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.notion.so',
  },
  {
    id: 'asana',
    name: 'Asana',
    category: ToolCategory.PROJECT_MANAGEMENT,
    description: 'Mature project management for teams that do more than just engineering. Strong for cross-functional work.',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://asana.com',
  },

  // ============================================================
  // AUTOMATION
  // ============================================================
  {
    id: 'zapier',
    name: 'Zapier',
    category: ToolCategory.AUTOMATION,
    description: 'No-code automation between 7000+ apps. AI Actions let LLMs trigger any workflow. The granddaddy of "if-this-then-that".',
    difficulty: Difficulty.BEGINNER,
    pricing: Pricing.FREEMIUM,
    website: 'https://zapier.com',
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: ToolCategory.AUTOMATION,
    description: 'Open-source, self-hostable Zapier alternative. Visual node-based workflows with strong AI/agent nodes.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://n8n.io',
  },
  {
    id: 'make',
    name: 'Make',
    category: ToolCategory.AUTOMATION,
    description: 'Visual automation platform (formerly Integromat). More expressive than Zapier — strong for complex multi-step flows.',
    difficulty: Difficulty.INTERMEDIATE,
    pricing: Pricing.FREEMIUM,
    website: 'https://www.make.com',
  },
];

// ============================================================
// CATEGORY COLOR MAP (for badges, modal accent bar, etc.)
// ============================================================
export const CATEGORY_COLORS: { [key in ToolCategory]: string } = {
  [ToolCategory.LANGUAGE_MODEL]: 'bg-sky-500/10 text-sky-400 border-sky-500/20',
  [ToolCategory.CODE_ASSISTANT]: 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20',
  [ToolCategory.IMAGE_GENERATION]: 'bg-purple-500/10 text-purple-400 border-purple-500/20',
  [ToolCategory.VIDEO_GENERATION]: 'bg-rose-500/10 text-rose-400 border-rose-500/20',
  [ToolCategory.DATA_SCIENCE]: 'bg-orange-500/10 text-orange-400 border-orange-500/20',
  [ToolCategory.VECTOR_DATABASE]: 'bg-cyan-500/10 text-cyan-400 border-cyan-500/20',
  [ToolCategory.FRAMEWORK]: 'bg-fuchsia-500/10 text-fuchsia-400 border-fuchsia-500/20',
  [ToolCategory.DATABASE]: 'bg-green-500/10 text-green-400 border-green-500/20',
  [ToolCategory.API_DEVELOPMENT]: 'bg-lime-500/10 text-lime-400 border-lime-500/20',
  [ToolCategory.VERSION_CONTROL]: 'bg-amber-500/10 text-amber-400 border-amber-500/20',
  [ToolCategory.CONTAINERIZATION]: 'bg-blue-500/10 text-blue-400 border-blue-500/20',
  [ToolCategory.CI_CD]: 'bg-pink-500/10 text-pink-400 border-pink-500/20',
  [ToolCategory.CLOUD_PLATFORM]: 'bg-indigo-500/10 text-indigo-400 border-indigo-500/20',
  [ToolCategory.DEPLOYMENT]: 'bg-teal-500/10 text-teal-400 border-teal-500/20',
  [ToolCategory.MONITORING]: 'bg-yellow-500/10 text-yellow-400 border-yellow-500/20',
  [ToolCategory.PROJECT_MANAGEMENT]: 'bg-violet-500/10 text-violet-400 border-violet-500/20',
  [ToolCategory.AUTOMATION]: 'bg-gray-500/10 text-gray-400 border-gray-500/20',
  [ToolCategory.CONCEPT]: 'bg-white/10 text-white border-white/20',
  [ToolCategory.AI_OBSERVABILITY]: 'bg-rose-600/10 text-rose-500 border-rose-600/20',
  [ToolCategory.AI_INFERENCE]: 'bg-orange-600/10 text-orange-500 border-orange-600/20',
  [ToolCategory.AGENT_ORCHESTRATION]: 'bg-indigo-600/10 text-indigo-500 border-indigo-600/20',
  [ToolCategory.DATA_INGESTION]: 'bg-lime-600/10 text-lime-500 border-lime-600/20',
};
